### ISSUE TITLE
Xamarin.Forms BinadableProperty issue

### ISSUE THREAD

**Issue by IndexOutOfLimit** [Fody/PropertyChanged#482]
I am getting below compilation error after upgrading PropertyChanged.Fody version to 3.2.1 with Xamarin.Forms 4.4 :
Fody: The type .. has a On_PropertyName_Changed method(..) which is static.

It was working fine with previous version (i.e. 3.1.3) with Xamarin.Forms 4.2.
I have one static BinadableProperty and propertyChanged method. 

Can you please let me know what might be the issue.
Thanks,

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.

**Comment by adrianknight89** [comment]
Just saw this issue as well.

**Comment by odinchiang** [comment]
Just saw this issue as well.
